#!/bin/sh
RED='\033[0;31m'
NC='\033[0m'
if ! head -1 "$1" | grep -qE "^(feat|fix|chore|docs|test|style|refactor|perf|build|ci|revert)(\(.+\)): .+"; then
    echo "${RED}Aborting commit. Your commit message must start with a valid type and follow the conventional format.${NC}" >&2
    exit 1
fi

if [ $(head -1 "$1" | wc -c) -gt 89 ]; then
    echo "${RED}Aborting commit. Your commit message is too long. It should not exceed 88 characters.${NC}" >&2
    exit 1
fi